import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "../components/providers/query-provider";
import { SubdomainProvider } from "../components/providers/subdomain-provider";
import { CondominioProvider } from "../components/providers/condominio-provider";
import { CondominioLoading } from "../components/providers/condominio-loading";
import { Toaster } from "react-hot-toast";
import { applyColorScript } from "@/lib/storage/apply-color-script";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vekino",
  description: "Generated by create next app",
  other: {
    "google-fonts": "Poppins",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: applyColorScript,
          }}
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        className={`${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <QueryProvider>
          <SubdomainProvider>
            <CondominioProvider>
              <CondominioLoading>
                {children}
              </CondominioLoading>
            </CondominioProvider>
            <Toaster
              position="top-center"
              toastOptions={{
                duration: 4000,
                style: {
                  background: '#fff',
                  color: '#333',
                },
                success: {
                  duration: 3000,
                  iconTheme: {
                    primary: '#10b981',
                    secondary: '#fff',
                  },
                },
                error: {
                  duration: 4000,
                  iconTheme: {
                    primary: '#ef4444',
                    secondary: '#fff',
                  },
                },
              }}
            />
          </SubdomainProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
